//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ClixStackDbModel", "Stack_StackLines", "Stack", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ClixStackDAL.Stack), "StackLine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClixStackDAL.StackLine), true)]

#endregion

namespace ClixStackDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClixStackDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ClixStackDbEntities object using the connection string found in the 'ClixStackDbEntities' section of the application configuration file.
        /// </summary>
        public ClixStackDbEntities() : base("name=ClixStackDbEntities", "ClixStackDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClixStackDbEntities object.
        /// </summary>
        public ClixStackDbEntities(string connectionString) : base(connectionString, "ClixStackDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClixStackDbEntities object.
        /// </summary>
        public ClixStackDbEntities(EntityConnection connection) : base(connection, "ClixStackDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StackLine> StackLines
        {
            get
            {
                if ((_StackLines == null))
                {
                    _StackLines = base.CreateObjectSet<StackLine>("StackLines");
                }
                return _StackLines;
            }
        }
        private ObjectSet<StackLine> _StackLines;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stack> Stacks
        {
            get
            {
                if ((_Stacks == null))
                {
                    _Stacks = base.CreateObjectSet<Stack>("Stacks");
                }
                return _Stacks;
            }
        }
        private ObjectSet<Stack> _Stacks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StackLines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStackLines(StackLine stackLine)
        {
            base.AddObject("StackLines", stackLine);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStacks(Stack stack)
        {
            base.AddObject("Stacks", stack);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClixStackDbModel", Name="Stack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stack object.
        /// </summary>
        /// <param name="stackId">Initial value of the StackId property.</param>
        public static Stack CreateStack(global::System.Int32 stackId)
        {
            Stack stack = new Stack();
            stack.StackId = stackId;
            return stack;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StackId
        {
            get
            {
                return _StackId;
            }
            set
            {
                if (_StackId != value)
                {
                    OnStackIdChanging(value);
                    ReportPropertyChanging("StackId");
                    _StackId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StackId");
                    OnStackIdChanged();
                }
            }
        }
        private global::System.Int32 _StackId;
        partial void OnStackIdChanging(global::System.Int32 value);
        partial void OnStackIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClixStackDbModel", "Stack_StackLines", "StackLine")]
        public EntityCollection<StackLine> StackLines
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StackLine>("ClixStackDbModel.Stack_StackLines", "StackLine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StackLine>("ClixStackDbModel.Stack_StackLines", "StackLine", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClixStackDbModel", Name="StackLine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StackLine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StackLine object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static StackLine CreateStackLine(global::System.Int32 id)
        {
            StackLine stackLine = new StackLine();
            stackLine.Id = id;
            return stackLine;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stack
        {
            get
            {
                return _Stack;
            }
            set
            {
                OnStackChanging(value);
                ReportPropertyChanging("Stack");
                _Stack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stack");
                OnStackChanged();
            }
        }
        private global::System.String _Stack;
        partial void OnStackChanging(global::System.String value);
        partial void OnStackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Line
        {
            get
            {
                return _Line;
            }
            set
            {
                OnLineChanging(value);
                ReportPropertyChanging("Line");
                _Line = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Line");
                OnLineChanged();
            }
        }
        private Nullable<global::System.Int32> _Line;
        partial void OnLineChanging(Nullable<global::System.Int32> value);
        partial void OnLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StackId
        {
            get
            {
                return _StackId;
            }
            set
            {
                OnStackIdChanging(value);
                ReportPropertyChanging("StackId");
                _StackId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StackId");
                OnStackIdChanged();
            }
        }
        private Nullable<global::System.Int32> _StackId;
        partial void OnStackIdChanging(Nullable<global::System.Int32> value);
        partial void OnStackIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClixStackDbModel", "Stack_StackLines", "Stack")]
        public Stack Stack1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stack>("ClixStackDbModel.Stack_StackLines", "Stack").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stack>("ClixStackDbModel.Stack_StackLines", "Stack").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Stack> Stack1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stack>("ClixStackDbModel.Stack_StackLines", "Stack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Stack>("ClixStackDbModel.Stack_StackLines", "Stack", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
